# usato come punto di entrata per tutti i playbook

- import_playbook: playbooks/bootstrap.yaml
- import_playbook: playbooks/setup-server.yaml
- import_playbook: playbooks/deploy-app-local.yaml
# - import_playbook: playbooks/deploy-app-prod.yaml
