# Per variabili sensibili

apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  # DATABASE_URL deve essere Base64. helm lo codifica in base al valore in values.yaml.
  # Quando deployi in produzione, devo usare --set per sovrascrivere questo valore.
  DATABASE_URL: {{ .Values.appSecrets.databaseUrl | b64enc | quote }}
  # In questo caso non mi interessa . uso un db locale