
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-db" (include "service-deployment-app.fullname" .) }}
  labels:
    {{ include "service-deployment-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: db
    app.kubernetes.io/instance: {{ .Release.Name }}
