  #  server http that redirects to https server
server {
    listen 80;
    
     return 301 https://$host$request_uri;
    # questo mi permette di usare i singoli pezzi come componenti individuali
}
# redirezione al server htts principale
server {
    # attivo anche http2
    listen 443 ssl http2;
    server_name miodominio.it;

    # certificati e key ssl
    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;
    # protocolli ssl
    ssl_protocols TLSv1.2 TLSv1.3;

    include /etc/nginx/conf.d/snippets/performance-gzip.conf;
    include /etc/nginx/conf.d/snippets/security-headers.conf;
    #  redirection to frotnend
    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }
    #  backend endpoints
    location /api/ {
        include /etc/nginx/conf.d/snippets/proxy-settings.conf;
        # container backend del docker compose yaml della folder 02
        proxy_pass http://api-service:3000/;
    }

}