# serveer http
    server {
        listen 80;
        server_name miodominio.it
        return 301 https://$host$request_uri

    }
    # redirect
    server {
        listen 443 ssl http2;
        server_name miodominio.it
        # cert e key ssl
        ssl_certificate /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;
        
        # specifico i protocolli ssl
        ssl_protocols TLSv1.2 TLSv1.3;

        # performance  with compression and cache
        gzip on;
        gzip_comp_level 6;
        gzip_types text/plain text/css application/json application/javascript;
        
        location ~* \.(?:ico|css|js|gif|jpe?g|png|svg)$ {
            expires 6M;
            add_header Cache-Control "public";
        }

        # security headers
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-XSS-Protection "1; mode=block";

        # recupero frontend
        location / {
            root /usr/share/nginx/html;
            try_files $uri /index.html;
        }

        # questo per gli endpoint backend
        location /api/ {
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # backend del file docker compose
            proxy_pass http://api-service:3000/;
        }
}