# uso http 1.1
proxy_http_version 1.1;

# Configurazione per supportare i websockets
#  lo metto solo se uso websockets
# proxy_set_header Upgrade $http_upgrade;
# proxy_set_header Connection 'upgrade';

# passo l'host del sito
proxy_set_header Host $host;

# PASSAGGIO DEGLI IP REALI questo mi serve sia per log che per la sicurezza lato be
# X-Real-IP -> Rappresenta l'ip dell'utente che ha fatto la request
proxy_set_header X-Real-IP $remote_addr;
# server per la catena degli ip
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
# permette di specificare se l'utente usa http o https
proxy_set_header X-Forwarded-Proto $scheme;

# evita che le risposte rimangano bloccate anche se il be è lento, restituisco almeno timeotu
proxy_connect_timeout 60s;
proxy_send_timeout 60s;
proxy_read_timeout 60s;