# server per non far capire al browser il tipo di file
add_header X-Content-Type-Options nosniff;
# uso questo header sotto per impledire attacchi di clickjacking (impedisce di integrare il sito in iframe)
add_header X-Frame-Options SAMEORIGIN;

# abilito la protezione per xss. in teoria i browser in teoria ora non lo usano più
#add_header X-XSS-Protection "1; mode=block";

# HSTS sarebbe Strict Transport Security che serve per forzare l'uso di HTTPS
# da usare solo se ho già configurato SSL/Certbot 
# add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;