apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-frontend" (include "service-deployment-app.fullname" .) }}
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      # 🔑 RIFERIMENTO AL SEGRETO DI PULL (Docker Hub)
      imagePullSecrets:
        - name: regcred 
      serviceAccountName: default # Usiamo l'account di servizio di default
      containers:
        - name: frontend-container
          image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}"
          imagePullPolicy: {{ .Values.images.frontend.pullPolicy }}
          ports:
            - name: http
              containerPort: 80 # Porta standard del frontend React/Nginx
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi